# Generated by Django 4.1.1 on 2022-10-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_email_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('movieId', models.IntegerField()),
            ],
        ),
    ]
