# Generated by Django 4.1.1 on 2022-10-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bookedticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookedTicket',
            new_name='BookedSeat',
        ),
    ]
